-- Day 01: Oracle SQL Practice

CREATE TABLE STUDENT
(
    STUDENT_ID NUMBER,
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER
);

INSERT INTO STUDENT
VALUES (1, 'Rohit', 22);

SELECT * FROM STUDENT;